services:
  - type: web
    name: attention-backend
    env: python
    buildCommand: python3 -m pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python3 app.py
    rootDir: backend
    

  - type: web
    name: attention-frontend
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
