services:
  - type: web
    name: attention-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py

  - type: web
    name: attention-frontend
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
